{
  "error": {
    "service": {
      "generic": "An internal error has occurred.",
      "timeout": "{{classname}}:: Error connection timeout:: {{endpoint}}",
      "unauthorized": "You don't have permission to access the required resource",
      "networkError": "Connection error. It has not been possible connect to server.",
      "notFound": "Resource not found",
      "methodNotAllowed": "Resource method not allowed"
    }
  },
  "identification": {
    "title": "Identity verification",
    "subtitle": "Enter the national ID number of the person to be verified.",
    "send": "Send",
    "message": "National ID number"
  },
  "message": {
    "title": "ID control completed",
    "message": "The identity verification process has been completed",
    "start": "Start a new identity verification"
  },
  "back": {
    "title": "Error Screen",
    "msg": "Cancel screen if trying to go back"
  },
  "scanner": {
    "error": "An error has occurred"
  }
}
